<div class="navbar-collapse collapse">
    <form class="navbar-form navbar-right" role="form" action="/session/login" method="post">
        <div class="form-group">
            <input name="email" type="text" placeholder="Email" class="form-control">
        </div>
        <div class="form-group">
            <input name="password" type="password" placeholder="Password" class="form-control">
        </div>
        <button type="submit" class="btn btn-success login-button">Вoйти</button>
    </form>
</div>